### ISSUE TITLE
 Data viewing for downloaded tags, etc.

### ISSUE THREAD

**Issue by BryceFury** [BryceFury/tumbly#5]
As title.

EDIT: Because I should've expanded and explained:

The ability to check the information that has been scraped alongside the image or image url.

At the moment, the url and note count are collected and put into the database in the photos table e.g.

 | photo_id | note_count |                  url                     |
----------------------------------------------
 |      1       |       100      | http://tumblr.com/image1 |
 |      2       |       5090    | http://tumblr.com/image2 |
 |      3       |       780      | http://tumblr.com/image3  |

I would like to find a way to display this information from the database once it has been added so:

- Read from the database.
- Display the image name/url in the GUI (either in an extended window or in a tab).
- Display the note count/photo id when the image/url name is selected.
- Display the tags from the tags table when the image/url name is selected.

Eventually the plan is to add the ability to scrape more data and display things like the most used tag.

Having written this out I realise that this is much more than a single feature so I may close this issue and open several based on individual features.

**Comment by rahul-kumi** [comment]
what do you expect to be done?

**Comment by rahul-kumi** [comment]
as you have mentioned,
it seems a lot,
so could you chunk the feature request and produce them as separate issues.

**Comment by BryceFury** [comment]
I have opened a load more issues that should be clearer and more focussed (at least more separate): #9 #10 #11 #12 #13 #14
